// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM1HXrz-gErhyoXBWbHIGTpwAUz1bcHM4',
    appId: '1:409183344836:web:9d44b67b62fe4c2d229191',
    messagingSenderId: '409183344836',
    projectId: 'my-parentcare-app',
    authDomain: 'my-parentcare-app.firebaseapp.com',
    storageBucket: 'my-parentcare-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ1uY-vodAGMXhNdsw-Xzu3pi0WfbEHP8',
    appId: '1:409183344836:android:267a51011b6fd1f7229191',
    messagingSenderId: '409183344836',
    projectId: 'my-parentcare-app',
    storageBucket: 'my-parentcare-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmf9_w6wcka5FGvHVOKS9eou_gDS3sS1M',
    appId: '1:409183344836:ios:0035aaa73a8071ec229191',
    messagingSenderId: '409183344836',
    projectId: 'my-parentcare-app',
    storageBucket: 'my-parentcare-app.firebasestorage.app',
    iosBundleId: 'com.example.parentCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmf9_w6wcka5FGvHVOKS9eou_gDS3sS1M',
    appId: '1:409183344836:ios:0035aaa73a8071ec229191',
    messagingSenderId: '409183344836',
    projectId: 'my-parentcare-app',
    storageBucket: 'my-parentcare-app.firebasestorage.app',
    iosBundleId: 'com.example.parentCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM1HXrz-gErhyoXBWbHIGTpwAUz1bcHM4',
    appId: '1:409183344836:web:e6b0ee357de3daeb229191',
    messagingSenderId: '409183344836',
    projectId: 'my-parentcare-app',
    authDomain: 'my-parentcare-app.firebaseapp.com',
    storageBucket: 'my-parentcare-app.firebasestorage.app',
  );

}