// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATKkCoULKHbWW2gb_gxkHLT9_gpn5E8Ns',
    appId: '1:824088659284:web:6f890408d1d1c2199eb4c1',
    messagingSenderId: '824088659284',
    projectId: 'parent-care-project',
    authDomain: 'parent-care-project.firebaseapp.com',
    storageBucket: 'parent-care-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9xPxX58nKJV4NAn2FTonnDKWCnJHIZ_I',
    appId: '1:824088659284:android:cb1ba7f5b9916c9e9eb4c1',
    messagingSenderId: '824088659284',
    projectId: 'parent-care-project',
    storageBucket: 'parent-care-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR1e24mL_AG66TQkJOIw8mjL59T5Y6q6c',
    appId: '1:824088659284:ios:99a2fd1e9b67aa4b9eb4c1',
    messagingSenderId: '824088659284',
    projectId: 'parent-care-project',
    storageBucket: 'parent-care-project.firebasestorage.app',
    iosBundleId: 'com.example.parentCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR1e24mL_AG66TQkJOIw8mjL59T5Y6q6c',
    appId: '1:824088659284:ios:99a2fd1e9b67aa4b9eb4c1',
    messagingSenderId: '824088659284',
    projectId: 'parent-care-project',
    storageBucket: 'parent-care-project.firebasestorage.app',
    iosBundleId: 'com.example.parentCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATKkCoULKHbWW2gb_gxkHLT9_gpn5E8Ns',
    appId: '1:824088659284:web:7eb1202d769574939eb4c1',
    messagingSenderId: '824088659284',
    projectId: 'parent-care-project',
    authDomain: 'parent-care-project.firebaseapp.com',
    storageBucket: 'parent-care-project.firebasestorage.app',
  );
}
